/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WageCal;

import javax.swing.*;
import java.io.*;



/**
 *
 * @author Eunah Kau
 */
public class Emp_WageCal extends javax.swing.JFrame {

    /**
     * Creates new form Emp_WageCal
     */
    public Emp_WageCal() {
        initComponents();
        
       loadEmployeeNames("D:/employee_names.txt", firstNameList,lastNameList);  
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FName = new javax.swing.JLabel();
        LName = new javax.swing.JLabel();
        firstNameList = new javax.swing.JComboBox();
        lastNameList = new javax.swing.JComboBox();
        positionPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cashierButton = new javax.swing.JRadioButton();
        salesAssociateButton = new javax.swing.JRadioButton();
        cleanerButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        hoursWorkedField = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 25, 112));
        jLabel1.setText("Employee Wages Calculator");

        FName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FName.setText("First Name:");

        LName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LName.setText("Last Name:");

        firstNameList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lastNameList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Position:");

        positionButtonGroup.add(cashierButton);
        cashierButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cashierButton.setText("Cashier");

        positionButtonGroup.add(salesAssociateButton);
        salesAssociateButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        salesAssociateButton.setText("Sales Associate");

        positionButtonGroup.add(cleanerButton);
        cleanerButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cleanerButton.setText("Cleaner");
        cleanerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout positionPanelLayout = new javax.swing.GroupLayout(positionPanel);
        positionPanel.setLayout(positionPanelLayout);
        positionPanelLayout.setHorizontalGroup(
            positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(positionPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(positionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashierButton)
                .addGap(52, 52, 52)
                .addComponent(salesAssociateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(cleanerButton)
                .addGap(34, 34, 34))
        );
        positionPanelLayout.setVerticalGroup(
            positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(positionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashierButton)
                    .addComponent(salesAssociateButton)
                    .addComponent(cleanerButton))
                .addGap(18, 18, 18))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Hours Worked:");

        CalculateButton.setBackground(new java.awt.Color(51, 204, 255));
        CalculateButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CalculateButton.setForeground(new java.awt.Color(0, 51, 153));
        CalculateButton.setText("Calculate Wages");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        clearButton.setBackground(new java.awt.Color(153, 255, 153));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(FName)
                .addGap(51, 51, 51)
                .addComponent(firstNameList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LName)
                .addGap(43, 43, 43)
                .addComponent(lastNameList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(hoursWorkedField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CalculateButton)
                            .addComponent(positionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LName)
                    .addComponent(firstNameList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(positionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hoursWorkedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(CalculateButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanerButtonActionPerformed
     
     

    
     private void loadEmployeeNames(String fileName, JComboBox<String> firstNameList, JComboBox<String> lastNameList) {
        firstNameList.removeAllItems(); // Clear the existing first name items
        lastNameList.removeAllItems(); // Clear the existing last name items
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split("\t");
                if (parts.length >= 2) {
                    firstNameList.addItem(parts[0]); // Add first name to first name dropdown list
                    lastNameList.addItem(parts[1]); // Add last name to last name dropdown list
                }
            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
      
  
      
    private double readHourlyRate(String fileName, String firstName, String lastName) {
    try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split("\t");
            if (parts.length >= 3 && parts[0].equals(firstName) && parts[1].equals(lastName)) {
                return Double.parseDouble(parts[2]);
            }
        }
    } catch (IOException | NumberFormatException e) {
        System.out.println(e.getMessage());
    }  
    return -1.0;
}
    
       
        private void writeToMergedFile(String fileName, String firstName, String lastName, String position, double hourlyRate, double hoursWorked, double wages) {
        try (PrintWriter writer = new PrintWriter(new FileWriter(fileName, true))) {
            writer.println("Name: " + firstName + " " + lastName);
            writer.println("Position: " + position);
            writer.println("Hourly Rate: $" + hourlyRate);
            writer.println("Hours Worked: " + hoursWorked);
            writer.println("Wages: $" + wages);
            writer.println();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        // TODO add your handling code here:
         try {
            double hoursWorked = Double.parseDouble(hoursWorkedField.getText());
            String firstName = (String) firstNameList.getSelectedItem();
            String lastName = (String) lastNameList.getSelectedItem();
            String position = " ";
            if (cashierButton.isSelected()) {
                position = "Cashier";
            } else if (salesAssociateButton.isSelected()) {
                position = "Sales Associate";
            } else if (cleanerButton.isSelected()) {
                position = "Cleaner";
            } else {
                JOptionPane.showMessageDialog(this, "Please select a position.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            double hourlyRate = readHourlyRate("D:/employee_rates.txt", firstName, lastName);

            double wages = hoursWorked * hourlyRate;
            textArea.setText("Name: " + firstName + " " + lastName + "\n");
            textArea.append("Position: " + position + "\n");
            textArea.append("Hourly Rate: $" + hourlyRate + "\n");
            textArea.append("Hours Worked: " + hoursWorked + "\n");
            textArea.append("Wages: $" + wages + "\n");

            writeToMergedFile("D:/merged_employee_info.txt", firstName, lastName, position, hourlyRate, hoursWorked, wages);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for hours worked.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
   
        
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
                // Clear the input fields and information display
                firstNameList.setSelectedIndex(0); // Reset selection
                lastNameList.setSelectedIndex(0); // Reset selection
                positionButtonGroup.clearSelection(); // Clear the selection of the radio buttons
                hoursWorkedField.setText(""); // Clear the text field
                textArea.setText(""); // Clear text area
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
         SwingUtilities.invokeLater(() -> {
             Emp_WageCal gui = new  Emp_WageCal();
            gui.setVisible(true);
        }); 
        
         
         
        
       
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_WageCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_WageCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_WageCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_WageCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_WageCal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel FName;
    private javax.swing.JLabel LName;
    private javax.swing.JRadioButton cashierButton;
    private javax.swing.JRadioButton cleanerButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox firstNameList;
    private javax.swing.JTextField hoursWorkedField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lastNameList;
    private javax.swing.ButtonGroup positionButtonGroup;
    private javax.swing.JPanel positionPanel;
    private javax.swing.JRadioButton salesAssociateButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}

